### ISSUE TITLE
Documentation missing for few fields

### ISSUE THREAD

**Issue by marius-dgmd** [loupeteam/LPM#38]
Hi Loupe team,

We have looked through the LPM code and tried it out and we have several questions that we couldn't find in the documentation and is not clear in the code as well:

1. Once a project is initialized with lpm init one can see in package.json this 'deploymentConfigs.StarterConfig" - what does this do?
2. There are several types of packages in the code - library packages, folder packages, project packages, HMI packages - is there somewhere we can find explanation on what the difference is? How are they created?

**Comment by Joshpolansky** [comment]
To add a few more details, 

Project and HMI Packages are meant to be "Templates" in that they are starts to new projects of that type. These may replace items.

For example, if you do an 

`lpm install starterasproject`

the package.json should not include startasproject as a depencency, and instead the enture file gets replaced with the package.json that is in the package.

The folder packages are Automation studio folder packages and contain information about where to put the package in the logical view and how to deploy the individual objects.

**Comment by marius-dgmd** [comment]
Thank you for the quick response.
